### ISSUE TITLE
ESP reboot when loading the project without certs

### ISSUE THREAD

**Issue by ZanzyTHEbar** [paclema/MQTTClient#12]
```
[  4372][E][vfs_api.cpp:24] open(): File system is not mounted
[  4378][E][MQTTClient.cpp:370] read_cert_file(): [MQTTClient] Failed to open file  for reading
```
MQTT Config
```json
{
  "mqtt": {
    "enabled": true,
    "reconnect_mqtt": true,
    "reconnect_retires": 10,
    "reconnect_time_ms": 10000,
    "server": "",
    "port": 1883,
    "id_name": "LEDController",
    "auth": false,
    "username": "",
    "password": "",
    "enable_certs": false,
    "ca_file": "",
    "cert_file": "",
    "key_file": "",
    "enabled_websocket": false,
    "websocket_path": "/",
    "pub_topic": [
      null
    ],
    "sub_topic": [
      "device/report",
    ]
  }
}
```

**Comment by ZanzyTHEbar** [comment]
I fixed the issue:
![image](https://github.com/paclema/MQTTClient/assets/45744329/5e70c88d-cfa5-4e7f-9a8d-43fa597d6dcf)
I originally had:
```cpp
mqttConfig["enable_certs"] = _deviceConfig.getMQTTConfig().enable_certs;
```
... oops.

**Comment by paclema** [comment]
Happy that you could fix your configuration error @ZanzyTHEbar !

I am not sure which part of the examples are out of date, I can not find anything wrong with them so far.  It is important that you use the configuration objects that the class expects, as explained in the [Library configuration](https://github.com/paclema/MQTTClient?tab=readme-ov-file#library-configuration),  otherwise, the MQTTClass is wrongly configured. And those objects are not random, you must use the names as explained.

Regarding adding these loading type-safe configurations, that would be a great extra protection to include in this library, thank you for the idea! Also, pull requests are welcome 😀

**Comment by ZanzyTHEbar** [comment]
You are right, my mistake. I was looking at out-dated examples on my local machine from changes i made to the library itself after my first issue was closed. i re-cloned your repo instead of using my local copy, and all examples are up to date. My apologies for the confusion. 

You are right once again, pr are welcome, haha - and I am considering making one. I am using the project in all of my MQTT projects since i discovered it.
